<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Telephone' => 'Teléfono',
    'Opening hours' => 'Horario',
    'Mobile phone' => 'Móvil',
    'Email' => 'Email',
    'Address' => 'Dirección',
    'Web name' => 'Nombre de la web',
    'Contact data' => 'Datos de contacto',
    'Keep enabled the fields you want to show.' => 'Mantener activados los campos que quiera que se muestren.',
    'Show title' => 'Mostrar título',
    'Contact us' => 'Contacte con nosotros',
    'Facebook' => '',
    'Twitter' => '',
    'Instagram' => '',
    'Pinterest' => '',
];
