<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'An error ocurred sending your email' => 'Ocurrió un error al enviar su email',
    'Incorrect captcha' => 'Código de seguridad incorrecto',
    'Send' => 'Enviar',
    'You must fill all fields' => 'Debe rellenar todos los campos',
    'Your email' => 'Email',
    'Your email has been sent successfully' => 'Su email se ha enviado correctamente',
    'Your message' => 'Mensaje',
    'Your name' => 'Nombre',
    'Security code'=>'Código de seguridad',
];
