<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Dirección',
    'Advanced' => 'Avanzado',
    'Coordinates takes precedence over address' => 'Las coordenadas prevalecen sobre la dirección',
    'Fit in row height' => 'Ajustar a la altura de la fila',
    'Google Map' => '',
    'Latitude' => 'Latitud',
    'Longitude' => 'Longitud',
    'Options' => 'Opciones',
    'Sattellite mode' => 'Modo satélite',
    'To use this block you must set the Googlemap Api key in General Settings' => 'Para usar éste bloque debe indicar una clave válida de la API de Googlemaps en ajustes generales',
    'Tooltip text' => 'Texto del marcador',
];
